version: '3.4'

services:
  webapi:
    image: pastebinlight_image
    environment:
      ConnectionStrings__Default: "Server=db; Database=PosteBinFP; User Id=sa; Password=ERz4anKub2O02!; Encrypt=Optional"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:80"
    

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "ERz4anKub2O02!"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
